### ISSUE TITLE
Změna závislostí v composeru

### ISSUE THREAD

**Issue by sinacek** [skaut/SkautisNette#15]
Koukal jsem, že máme závislost v composeru na nette 2.1@dev a na skautis@dev což bych odtranil ať nejsou závisloti na dev verzích, když stejně už neprobíhá tak rychlý vývoj aby to mělo smysl. 

S tím jsem rovnou založil nové větve 2.3 a 2.4 aby byly měla i každá verze nette svojí verzi a bylo to v daném projektu jasnější. 
https://github.com/skaut/SkautisNette/branches

Nastavil bych tu větev 2.4 jako výchozí pokud souhlasíte. 

Sin

**Comment by sinacek** [comment]
@JindrichPilar Udělal by jsi release 2.3.0 a 2.4.0?

**Comment by xificurk** [comment]
"~2.1@dev" není závislost na dev verzi. To je požadavek na jakoukoliv verzi 2.1 - 3.0. Stability flag '@dev' říká, že se může nainstalovat i dev verze splňující předchozí podmínku, ale uplatňuje se jen a pouze, pokud je toto root balíček. Toto je velice užitečné kvůli testování kompatibility s ještě neotagovanými verzemi závislostí. Zároveň nikdo, kdo používá tento balíček nedostane dev verzi skautisu nebo nette, pokud si ji sám explicitně nevyžádá.

Dodatečné větve 2.3 a 2.4 mi přijdou zbytečné. Současná verze podporuje i novější verze nette... Další větve nemají žádný reálný přínos. Ale koukám, že by se do travisu mělo přidat testování proti novějším verzím PHP i Nette.

Pokud by se měla otvírat nová větev, tak bych spíš začal pracovat na 3.x, která by zahodila zpětnou kompatibilitu se staršími verzemi Nette i PHP... minimální požadavky bych bumpnul na PHP 7.0 (možná 7.1) a připravované Nette 3.0.

**Comment by sinacek** [comment]
Aha, tak to jsem ten @dev špatně chápal. Tedy pokud vám to příjde jako zbytečné, tak já je zase smažu, nemám s tím problém.

Nápad verze 3.0 pro Nette 2.4 a PHP 7.1 se mi líbí.

**Comment by xificurk** [comment]
Myslel jsem 3.0 pro (zatím) nevydané Nette 3.0 ;)

**Comment by sinacek** [comment]
ok, ja to tedy zatím zrušil
