### ISSUE TITLE
Packagist hook

### ISSUE THREAD

**Issue by xificurk** [skaut/SkautisNette#5]
Vypadá to, že je nějak rozbitá synchronizace na [packagist](https://packagist.org/packages/skautis/nette)
Krom toho, že se neaktualizovala reference na `2.x-dev`, tak tam jsou i přimíchané i odkazy do https://github.com/sinacek/* a `master-dev` verze, která netuším, kde se vzala.
Přitom hook tady na githubu žádnou chybu nehlásí... Nějaké nápady @sinacek ?

**Comment by sinacek** [comment]
Ahoj,
do úterý musím dopsat diplomku,takže tedka mě nic nenapadá, ale přidal jsem tě na packigistu, abys k tomu tam měl taky přístup. Pokud tam teda jsi taky jako xificurk.

**Comment by xificurk** [comment]
Jo, to jsem já. Dik, mrknu na to.

**Comment by xificurk** [comment]
Odstranil jsem `master-dev` a opravil malé "s" na velké v adrese repa na githubu a packagist se korektně aktualizoval...
Issue zatím nechávám otevřené, dokud se neověří, že funguje automatický hook z githubu.

**Comment by xificurk** [comment]
Vypadá to, že poslední změny se korektně promítly i v definici balíčku na packagist.org, takže zavírám.
